routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

// UI Routes
Route::get('/', 'HomeController@index')->name('home');

Route::get('/blog', 'ArticleController@index');
Route::get('/articles/{articleSlug}', 'ArticleController@single');

Route::get('/products', 'ProductController@index');
Route::get('/products/{productSlug}', 'ProductController@single');

Route::resource('/cart', 'CartController')->except(['show']);
// Route::post('/cart/quantity-change', 'CartController@quantityChange')->name('cart.quantityChange');


Route::prefix('checkout')->group(function () {
    Route::get('/', 'CheckoutController@index')->name('checkout.index');
    Route::post('/city', 'CheckoutController@getCity')->name('checkout.city');
    Route::post('/apply-discount', 'CheckoutController@applyDiscount')->name('checkout.applyDiscount');
    Route::post('/change-price-transportation', 'CheckoutController@changePriceTransportation')->name('checkout.changePriceTransportation');
});

Route::post('/comment', 'HomeController@comment')->middleware('auth');
Route::get('/articles/category/{categorySlug}', 'CategoryController@index')->name('categories');
Route::get('/articles/tag/{tagSlug}', 'TagController@index')->name('tags');

// ADMIN Routes
Route::namespace('Admin')->prefix('admin')->group(function () {
    Route::get('/', 'DashboardController@index')->name('admin.dashboard');
    Route::post('/dashboard/upload-image', 'DashboardController@uploadImageSubject')->name('admin.upload');

    Route::resource('articles', 'ArticleController')->except(['show', 'destroy']);
    Route::get('/articles/status/update', 'ArticleController@status')->name('articles.status');
    Route::post('/articles/delete', 'ArticleController@delete')->name('articles.delete');

    Route::resource('products', 'ProductController')->except(['show', 'destroy']);
    Route::get('/products/status/update', 'ProductController@status')->name('products.status');
    Route::post('/products/delete', 'ProductController@delete')->name('products.delete');
    Route::post('/products/delete-image', 'ProductController@deleteImage')->name('products.deleteImage');

    Route::resource('categories', 'CategoryController')->except(['show', 'destroy']);
    Route::get('/categories/status/update', 'CategoryController@status')->name('categories.status');
    Route::post('/categories/delete', 'CategoryController@delete')->name('categories.delete');

    Route::resource('menus', 'MenuController')->except(['show', 'destroy']);
    Route::get('/menus/status/update', 'MenuController@status')->name('menus.status');
    Route::post('/menus/delete', 'MenuController@delete')->name('menus.delete');

    Route::resource('tags', 'TagController')->except(['show', 'destroy']);
    Route::get('/tags/status/update', 'TagController@status')->name('tags.status');
    Route::post('/tags/delete', 'TagController@delete')->name('tags.delete');

    Route::get('/comments', 'CommentController@index')->name('comments.index');
    Route::get('/comments/status/update', 'CommentController@status')->name('comments.status');
    Route::post('/comments/delete', 'CommentController@delete')->name('comments.delete');
    Route::get('/comments/unsuccessful', 'CommentController@unsuccessful')->name('comments.approved');

    Route::resource('roles', 'RoleController')->except(['show', 'destroy']);
    Route::post('/roles/delete', 'RoleController@delete')->name('roles.delete');

    Route::resource('permissions', 'PermissionController')->except(['show', 'destroy']);
    Route::post('/permissions/delete', 'PermissionController@delete')->name('permissions.delete');

    Route::resource('coupons', 'CouponController')->except(['show']);
    Route::get('/coupons/status/update', 'CouponController@status')->name('coupons.status');

    Route::resource('transportations', 'TransportationController')->except(['show']);
    Route::get('/transportations/status/update', 'TransportationController@status')->name('transportations.status');
});

app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use App\Http\Requests\RoleRequest;


class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $roles = Role::with('permissions')->get();

        return view('admin.roles.index', compact('roles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $permissions = Permission::all();
        return view('admin.roles.create', compact('permissions'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(RoleRequest $request)
    {
        $role = Role::create([
            'name' => $request->name,
            'description' => $request->description,
        ]);
        $role->syncPermissions($request->permission_id);

        return redirect(route('roles.index'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Role $role)
    {
        $permissions = Permission::all();
        return view('admin.roles.edit', compact('role', 'permissions'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(RoleRequest $request, Role $role)
    {
        $role->update([
            'name' => $request->name,
            'description' => $request->description,
        ]);
        $role->syncPermissions($request->permission_id);

        return redirect(route('roles.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function delete(Request $request)
    {
        $role = Role::findOrFail($request->id);
        $role->delete();
    }
}

resources/views/admin/roles/create.blade.php
@extends('admin.layouts.master')
@section('title' , 'ثبت نقش')

@section('content')
  <section>
    <div class="row">
      <div class="col-12">
        <div class="card-box">
            <div class="head-section">
                <h4>ثبت نقش جدید</h4>
                <a href="{{ route('roles.index') }}" class="btn btn-primary btn-sm">مشاهده نقش ها</a>
            </div>
            <hr>
            @include('admin.section.errors')
            <div class="row">
              <div class="col-lg-12">
                <form class="form-horizontal" action="{{ route('roles.store') }}" method="post">
                @csrf
                  <div class="form-group">
                    <label for="name">نام نقش</label> <small><span class="text-danger">به صورت انگلیسی نوشته شود.</span></small>
                    <input type="text" class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" name="name" value="{{old('name')}}">
                  </div>
                  <div class="form-group">
                    <label for="description">توضیحات نقش</label>
                    <input type="text" class="form-control {{ $errors->has('description') ? 'is-invalid' : '' }}" name="description" value="{{old('description')}}" />
                  </div>
                  <div class="form-group">
                    <label for="permission_id">مجوزها</label>
                    <select name="permission_id[]" class="selectpicker" multiple data-selected-text-format="count > 3" data-live-search="true" data-style="btn btn-outline-primary">
                      @foreach ($permissions as $permission)
                        <option value="{{$permission->id}}">{{$permission->name}} - {{$permission->description}}</option>                          
                      @endforeach  
                    </select>
                  </div>
                  <br>
                  <div class="form-group">
                    <button type="submit" class="btn btn-success btn-block">ثبت نقش</button>
                    <a href="{{ route('roles.index') }}" class="btn btn-secondary btn-block">کنسل</a>
                  </div>
                </form>
              </div>
            </div>
        </div>
      </div>     
    </div>
  </section>
@endsection

resources/views/admin/roles/edit.blade.php
@extends('admin.layouts.master')
@section('title' , 'ویرایش نقش ها')

@section('content')
  <section>
    <div class="row">
      <div class="col-12">
          <div class="card-box">
              <div class="head-section">
                  <h4>ویرایش نقش</h4>
                  <a href="{{ route('roles.index') }}" class="btn btn-primary btn-sm">مشاهده نقش ها</a>
              </div>
              <hr>
              @include('admin.section.errors')
              <div class="row">
                <div class="col-lg-12">
                  <form class="form-horizontal" action="{{ route('roles.update' , ['role'=> $role->id]) }}" method="post">
                    @method('PATCH')
                    @csrf
                    <div class="form-group">
                      <label for="name">نام نقش</label>
                      <input type="text" class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" name="name" value="{{ $role->name }}">
                    </div>
                    <div class="form-group">
                      <label for="description">توضیحات نقش</label>
                      <input type="text" class="form-control {{ $errors->has('description') ? 'is-invalid' : '' }}" name="description" value="{{ $role->description }}" />
                    </div>
                    <div class="form-group">
                      <label for="permission_id">مجوزها</label>
                      <select name="permission_id[]" class="selectpicker" multiple data-selected-text-format="count > 4" data-live-search="true" data-style="btn btn-outline-primary">
                        @foreach ($permissions as $permission)
                          <option value="{{$permission->id}}" {{in_array(trim($permission->id) , $role->permissions->pluck('id')->toArray()) ? 'selected' : ''}}>{{$permission->name}} - {{$permission->description}}</option>                          
                        @endforeach  
                      </select>
                    </div>
                    <br>
                    <div class="form-group">
                      <button type="submit" class="btn btn-success btn-block">ویرایش نقش</button>
                      <a href="{{ route('roles.index') }}" class="btn btn-secondary btn-block">کنسل</a>
                    </div>
                  </form>
                </div>
              </div>
        </div>
      </div>     
    </div>
  </section>
@endsection

resources/views/admin/roles/index.blade.php
@extends('admin.layouts.master')
@section('title' , 'نقش ها')
@section('content')
<section>
    <div class="row">
        <div class="col-12">
            <div class="card-box">
                <div class="head-section">
                    <h4>نقش ها</h4>
                    <div class="btn-group-sm">
                        <a href="{{ route('roles.create') }}" class="btn btn-primary btn-sm">ایجاد نقش جدید</a>
                        <a href="{{ route('permissions.index') }}" class="btn btn-success btn-sm">مجوزها</a>
                    </div>
                </div>
                <p class="text-muted font-13 m-b-30">
                    تمام نقش ها در زیر به نمایش گذاشته شده است.
                </p>
                <div class="table-responsive-sm">
                    <table id="datatable" class="table table-bordered table-hover dt-responsive">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>عنوان</th>
                            <th>توضیحات</th>
                            <th>اجازه دسترسی</th>
                            <th>تنظیمات</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach ($roles as $i => $role)
                            <tr>
                                <td>{{++$i}}</td>
                                <td>{{$role->name}}</td>
                                <td>{{$role->description}}</td>
                                <td>
                                    @if (count($role->permissions))
                                        <ul>
                                            @foreach ($role->permissions as $permission)
                                            <li>{{$permission->name}} - {{$permission->description}}</li>
                                            @endforeach    
                                        </ul>
                                    @else
                                        <span class="text-warning">برای این نقش مجوزی داده نشد است!</span>
                                    @endif
                                </td>
                                <td>
                                    <div class="btn-group-sm d-flex justify-content-xl-between">
                                        <a href="{{ route('roles.delete', ['role' => $role->id]) }}" title="حذف" class="btn btn-sm deleterole" data-id="{{ $role->id }}">
                                            <i class="fas fa-trash text-danger"></i>
                                        </a>
                                        <a href="{{ route('roles.edit', ['role' => $role->id]) }}" title="ویرایش" class="btn btn-sm">
                                            <i class="fas fa-edit"></i>
                                        </a>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- end row -->
</section>
@endsection

@section('styles')
    <meta name="csrf-token" content="{{ csrf_token() }}">
@endsection

@section('scripts')
    {{-- Confirm Delete --}}
<script>
    //  Delete Confirm 
    $('.deleterole').on('click', function (e) {
        e.preventDefault();

        let le = $(this);
        let url = le.attr('href');
        let CSRF_TOKEN = $('meta[name="csrf-token"]').attr('content');
        let id = $(this).data('id');

        const swalWithBootstrapButtons = Swal.mixin({
        customClass: {
            confirmButton: 'btn btn-success',
            cancelButton: 'btn btn-danger'
        },
        buttonsStyling: false
        })

        swalWithBootstrapButtons.fire({
            title: 'مطمئن هستید?',
            text: "بعد از حذف شما قادر به بازیابی اطلاعات نیستید!",
            type: 'warning',
            showCancelButton: true,
            confirmButtonText: 'حذف',
            cancelButtonText: 'کنسل',
            reverseButtons: true
        }).then((result) => {
            if (result.value) {
                $.ajax({
                    url: url,
                    type: "POST",
                    data: {
                        'id': id,
                        '_token': CSRF_TOKEN
                    },
                    success: function (res) {  
                        
                        swalWithBootstrapButtons.fire(
                                'حذف شد!',
                                'اطلاعات شما به طور کامل حذف شد',
                                'success'
                            )
                            setInterval(function() {location.reload();}, 2000);
                    }
                });
            }else if (result.dismiss === Swal.DismissReason.cancel) {
                swalWithBootstrapButtons.fire(
                'کنسل شد',
                'اطلاعات موردنظر هنوز در دسترس شماست :)',
                'error'
                )
            }
        });
    });

</script>
@endsection