routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

// UI Routes
Route::get('/', 'HomeController@index')->name('home');

Route::get('/blog', 'ArticleController@index');
Route::get('/articles/{articleSlug}', 'ArticleController@single');

Route::get('/products', 'ProductController@index');
Route::get('/products/{productSlug}', 'ProductController@single');

Route::resource('/cart', 'CartController')->except(['show']);
// Route::post('/cart/quantity-change', 'CartController@quantityChange')->name('cart.quantityChange');


Route::prefix('checkout')->group(function () {
    Route::get('/', 'CheckoutController@index')->name('checkout.index');
    Route::post('/city', 'CheckoutController@getCity')->name('checkout.city');
    Route::post('/apply-discount', 'CheckoutController@applyDiscount')->name('checkout.applyDiscount');
    Route::post('/change-price-transportation', 'CheckoutController@changePriceTransportation')->name('checkout.changePriceTransportation');
});

Route::post('/comment', 'HomeController@comment')->middleware('auth');
Route::get('/articles/category/{categorySlug}', 'CategoryController@index')->name('categories');
Route::get('/articles/tag/{tagSlug}', 'TagController@index')->name('tags');

// ADMIN Routes
Route::namespace('Admin')->prefix('admin')->group(function () {
    Route::get('/', 'DashboardController@index')->name('admin.dashboard');
    Route::post('/dashboard/upload-image', 'DashboardController@uploadImageSubject')->name('admin.upload');

    Route::resource('articles', 'ArticleController')->except(['show', 'destroy']);
    Route::get('/articles/status/update', 'ArticleController@status')->name('articles.status');
    Route::post('/articles/delete', 'ArticleController@delete')->name('articles.delete');

    Route::resource('products', 'ProductController')->except(['show', 'destroy']);
    Route::get('/products/status/update', 'ProductController@status')->name('products.status');
    Route::post('/products/delete', 'ProductController@delete')->name('products.delete');
    Route::post('/products/delete-image', 'ProductController@deleteImage')->name('products.deleteImage');

    Route::resource('categories', 'CategoryController')->except(['show', 'destroy']);
    Route::get('/categories/status/update', 'CategoryController@status')->name('categories.status');
    Route::post('/categories/delete', 'CategoryController@delete')->name('categories.delete');

    Route::resource('menus', 'MenuController')->except(['show', 'destroy']);
    Route::get('/menus/status/update', 'MenuController@status')->name('menus.status');
    Route::post('/menus/delete', 'MenuController@delete')->name('menus.delete');

    Route::resource('tags', 'TagController')->except(['show', 'destroy']);
    Route::get('/tags/status/update', 'TagController@status')->name('tags.status');
    Route::post('/tags/delete', 'TagController@delete')->name('tags.delete');

    Route::get('/comments', 'CommentController@index')->name('comments.index');
    Route::get('/comments/status/update', 'CommentController@status')->name('comments.status');
    Route::post('/comments/delete', 'CommentController@delete')->name('comments.delete');
    Route::get('/comments/unsuccessful', 'CommentController@unsuccessful')->name('comments.approved');

    Route::resource('roles', 'RoleController')->except(['show', 'destroy']);
    Route::post('/roles/delete', 'RoleController@delete')->name('roles.delete');

    Route::resource('permissions', 'PermissionController')->except(['show', 'destroy']);
    Route::post('/permissions/delete', 'PermissionController@delete')->name('permissions.delete');

    Route::resource('coupons', 'CouponController')->except(['show']);
    Route::get('/coupons/status/update', 'CouponController@status')->name('coupons.status');

    Route::resource('transportations', 'TransportationController')->except(['show']);
    Route::get('/transportations/status/update', 'TransportationController@status')->name('transportations.status');
});

app/Transportation.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Transportation extends Model
{
    protected $fillable = ['title', 'description', 'price', 'status'];
}

app/Http/Controllers/Admin/TransportationController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Transportation;
use Illuminate\Http\Request;
use App\Http\Requests\TransportationRequest;

class TransportationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $transportations = Transportation::all();
        return view('admin.transportations.index', compact('transportations'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.transportations.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(TransportationRequest $request)
    {
        Transportation::create($request->all());
        return redirect(route('transportations.index'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Transportation  $transportation
     * @return \Illuminate\Http\Response
     */
    public function edit(Transportation $transportation)
    {
        return view('admin.transportations.edit', compact('transportation'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Transportation  $transportation
     * @return \Illuminate\Http\Response
     */
    public function update(TransportationRequest $request, Transportation $transportation)
    {
        $transportation->update($request->all());
        return redirect(route('transportations.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Transportation  $transportation
     * @return \Illuminate\Http\Response
     */
    public function destroy(Transportation $transportation)
    {
        $transportation->delete();
    }

    public function status(Request $request)
    {
        $transportation = Transportation::findOrFail($request->id);
        $transportation->status = $request->status;
        $transportation->save();
    }
}

resources/views/admin/transportations/create.blade.php
@extends('admin.layouts.master')
@section('title' , 'ثبت حمل و نقل')

@section('content')
<section>
  <div class="row">
    <div class="col-12">
      <div class="card-box">
        <div class="head-section">
          <h4>ثبت حمل و نقل جدید</h4>
          <a href="{{ route('transportations.index') }}" class="btn btn-primary btn-sm">مشاهده حمل و نقل ها</a>
        </div>
        <hr>
        @include('Admin.section.errors')
        <div class="row">
          <div class="col-lg-12">
            <form class="form-horizontal" action="{{ route('transportations.store') }}" method="post">
              @csrf
              <div class="form-group">
                <div class="row">
                  <div class="col-md-6">
                    <label for="title">عنوان</label>
                    <input type="text" class="form-control" name="title" value="{{old('title')}}">
                </div>
                  <div class="col-md-6">
                      <label for="price">قیمت</label>
                      <input type="text" class="form-control" name="price" value="{{old('price')}}">
                  </div>
                </div>
              </div>
              <div class="form-group">
                  <label for="description">توضیحات</label>
                  <textarea rows="3" class="form-control" name="description" >{{old('description')}}</textarea>
              </div>
              <br>
              <div class="form-group">
                <button type="submit" class="btn btn-success btn-block">ثبت حمل و نقل</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
@endsection

resources/views/admin/transportations/edit.blade.php
@extends('admin.layouts.master')
@section('title' , 'ویرایش حمل و نقل')

@section('content')
<section>
  <div class="row">
    <div class="col-12">
      <div class="card-box">
        <div class="head-section">
          <h4>ویرایش حمل و نقل</h4>
          <a href="{{ route('transportations.index') }}" class="btn btn-primary">مشاهده حمل و نقل ها</a>
        </div>
        <hr>
        @include('Admin.section.errors')
        <div class="row">
          <div class="col-lg-12">
            <form class="form-horizontal" action="{{ route('transportations.update', ['transportation' => $transportation->id]) }}"
              method="post">
              @csrf
              @method('PATCH')
              <div class="form-group">
                <div class="row">
                  <div class="col-md-6">
                    <label for="title">عنوان</label>
                    <input type="text" class="form-control" name="title" value="{{$transportation->title}}">
                </div>
                  <div class="col-md-6">
                      <label for="price">قیمت</label>
                      <input type="text" class="form-control" name="price" value="{{$transportation->price}}">
                  </div>
                </div>
              </div>
              <div class="form-group">
                  <label for="description">توضیحات</label>
                  <textarea rows="3" class="form-control" name="description">{{$transportation->description}}</textarea>
              </div>
              <br>
              <div class="form-group">
                <button type="submit" class="btn btn-success btn-block">ویرایش حمل و نقل</button>
                <a href="{{ route('transportations.index') }}" class="btn btn-secondary btn-block">کنسل</a>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
@endsection

resources/views/admin/transportations/index.blade.php
@extends('admin.layouts.master')
@section('title' , 'حمل و نقل ها')

@section('content')
<section>
    <div class="row">
        <div class="col-12">
            <div class="card-box">
                <div class="head-section">
                    <h4>حمل و نقل ها</h4>
                    <a href="{{ route('transportations.create') }}" class="btn btn-primary btn-sm">ثبت حمل و نقل جدید</a>
                </div>
                <p class="text-muted font-13 m-b-30">
                    تمام روش های حمل و نقل در زیر به نمایش گذاشته شده است.
                </p>
                <div class="table-responsive-sm">
                    <table id="datatable" class="table table-bordered table-hover dt-responsive">
                        <thead>
                            <tr>
                                <th>عنوان</th>
                                <th>توضیحات</th>
                                <th>مبلغ</th>
                                <th>تنظیمات</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($transportations as $transportation)
                            <tr>
                                <td>{{$transportation->title}}</td>
                                <td>{{$transportation->description}}</td>
                                <td>{{$transportation->price}}</td>
                                <td>
                                    <div class="btn-group-sm d-flex justify-content-xl-between">
                                        <input type="checkbox" data-id="{{ $transportation->id }}" name="status"
                                            class="js-switch" {{ $transportation->status == 1 ? 'checked' : '' }}>
                                        <a href="{{ route('transportations.edit', ['transportation' => $transportation->id]) }}"
                                            class="btn btn-sm" title="ویرایش">
                                            <i class="fas fa-edit"></i>
                                        </a>
                                        <a href="{{ route('transportations.destroy', ['transportation' => $transportation->id]) }}"
                                            title="حذف" class="btn btn-sm deleted" data-id="{{ $transportation->id }}">
                                            <i class="fas fa-trash text-danger"></i>
                                        </a>
                                    </div>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- end row -->
</section>
@endsection


@section('styles')
{{-- Switchery Style --}}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/switchery/0.8.2/switchery.min.css">
@endsection

@section('scripts')

{{-- Switchery Scripts --}}
<script src="https://cdnjs.cloudflare.com/ajax/libs/switchery/0.8.2/switchery.min.js"></script>
<script>
    let elems = Array.prototype.slice.call(document.querySelectorAll('.js-switch'));

    elems.forEach(function(html) {
        let switchery = new Switchery(html,  { size: 'small' });
    });
</script>

{{-- Change Status and Confirm Delete --}}
<script>
    // Change Status 
    $(document).ready(function(){
        $('.js-switch').change(function () {
        let status = $(this).prop('checked') === true ? 1 : 0;
        let id = $(this).data('id');
        $.ajax({
            type: "GET",
            dataType: "json",
            url: '{{ route('transportations.status') }}',
            data: {'status': status, 'id': id}
            });
        });
    });
//  Delete Confirm 
    $('.deleted').on('click', function (e) {
        e.preventDefault();

        let le = $(this);
        let url = le.attr('href');
        let CSRF_TOKEN = $('meta[name="csrf-token"]').attr('content');
        let id = $(this).data('id');

        const swalWithBootstrapButtons = Swal.mixin({
        customClass: {
            confirmButton: 'btn btn-success',
            cancelButton: 'btn btn-danger'
        },
        buttonsStyling: false
        })

        swalWithBootstrapButtons.fire({
            title: 'مطمئن هستید?',
            text: "بعد از حذف شما قادر به بازیابی اطلاعات نیستید!",
            type: 'warning',
            showCancelButton: true,
            confirmButtonText: 'حذف',
            cancelButtonText: 'کنسل',
            reverseButtons: true
        }).then((result) => {
            if (result.value) {
                $.ajax({
                    url: url,
                    type: "DELETE",
                    data: {
                        'id': id,
                        '_token': CSRF_TOKEN
                    },
                    success: function (res) {  
                        
                        swalWithBootstrapButtons.fire(
                                'حذف شد!',
                                'اطلاعات شما به طور کامل حذف شد',
                                'success'
                            )
                            setInterval(function() {location.reload();}, 2000);
                    }
                });
            }else if (result.dismiss === Swal.DismissReason.cancel) {
                swalWithBootstrapButtons.fire(
                'کنسل شد',
                'اطلاعات موردنظر هنوز در دسترس شماست :)',
                'error'
                )
            }
        });
    });

</script>
@endsection