routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

// UI Routes
Route::get('/', 'HomeController@index')->name('home');

Route::get('/blog', 'ArticleController@index');
Route::get('/articles/{articleSlug}', 'ArticleController@single');

Route::get('/products', 'ProductController@index');
Route::get('/products/{productSlug}', 'ProductController@single');

Route::resource('/cart', 'CartController')->except(['show']);
// Route::post('/cart/quantity-change', 'CartController@quantityChange')->name('cart.quantityChange');


Route::prefix('checkout')->group(function () {
    Route::get('/', 'CheckoutController@index')->name('checkout.index');
    Route::post('/city', 'CheckoutController@getCity')->name('checkout.city');
    Route::post('/apply-discount', 'CheckoutController@applyDiscount')->name('checkout.applyDiscount');
    Route::post('/change-price-transportation', 'CheckoutController@changePriceTransportation')->name('checkout.changePriceTransportation');
});

Route::post('/comment', 'HomeController@comment')->middleware('auth');
Route::get('/articles/category/{categorySlug}', 'CategoryController@index')->name('categories');
Route::get('/articles/tag/{tagSlug}', 'TagController@index')->name('tags');

// ADMIN Routes
Route::namespace('Admin')->prefix('admin')->group(function () {
    Route::get('/', 'DashboardController@index')->name('admin.dashboard');
    Route::post('/dashboard/upload-image', 'DashboardController@uploadImageSubject')->name('admin.upload');

    Route::resource('articles', 'ArticleController')->except(['show', 'destroy']);
    Route::get('/articles/status/update', 'ArticleController@status')->name('articles.status');
    Route::post('/articles/delete', 'ArticleController@delete')->name('articles.delete');

    Route::resource('products', 'ProductController')->except(['show', 'destroy']);
    Route::get('/products/status/update', 'ProductController@status')->name('products.status');
    Route::post('/products/delete', 'ProductController@delete')->name('products.delete');
    Route::post('/products/delete-image', 'ProductController@deleteImage')->name('products.deleteImage');

    Route::resource('categories', 'CategoryController')->except(['show', 'destroy']);
    Route::get('/categories/status/update', 'CategoryController@status')->name('categories.status');
    Route::post('/categories/delete', 'CategoryController@delete')->name('categories.delete');

    Route::resource('menus', 'MenuController')->except(['show', 'destroy']);
    Route::get('/menus/status/update', 'MenuController@status')->name('menus.status');
    Route::post('/menus/delete', 'MenuController@delete')->name('menus.delete');

    Route::resource('tags', 'TagController')->except(['show', 'destroy']);
    Route::get('/tags/status/update', 'TagController@status')->name('tags.status');
    Route::post('/tags/delete', 'TagController@delete')->name('tags.delete');

    Route::get('/comments', 'CommentController@index')->name('comments.index');
    Route::get('/comments/status/update', 'CommentController@status')->name('comments.status');
    Route::post('/comments/delete', 'CommentController@delete')->name('comments.delete');
    Route::get('/comments/unsuccessful', 'CommentController@unsuccessful')->name('comments.approved');

    Route::resource('roles', 'RoleController')->except(['show', 'destroy']);
    Route::post('/roles/delete', 'RoleController@delete')->name('roles.delete');

    Route::resource('permissions', 'PermissionController')->except(['show', 'destroy']);
    Route::post('/permissions/delete', 'PermissionController@delete')->name('permissions.delete');

    Route::resource('coupons', 'CouponController')->except(['show']);
    Route::get('/coupons/status/update', 'CouponController@status')->name('coupons.status');

    Route::resource('transportations', 'TransportationController')->except(['show']);
    Route::get('/transportations/status/update', 'TransportationController@status')->name('transportations.status');
});

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;

class Article extends Model
{
    use Sluggable;

    protected $fillable = [
        'title', 'description', 'body',
    ]; 

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'title'
            ]
        ];
    }

     /**
     * Get the post's image.
     */
    public function image()
    {
        return $this->morphOne('App\Image', 'imageable');
    }

    public function path()
    {
        return "/articles/$this->slug";
    }

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function categories()
    {
        return $this->belongsToMany('App\Category');
    }

    public function tags()
    {
        return $this->morphToMany('App\Tag', 'taggable');
    }

    /**
     * Get all of the post's comments.
     */
    public function comments()
    {
        return $this->morphMany('App\Comment', 'commentable');
    }
}

app/Http/Controllers/Admin/ArticleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Article;
use App\Category;
use App\Tag;
use App\Image;
use App\Http\Requests\ArticleRequest;
use Illuminate\Http\Request;

class ArticleController extends AdminController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $articles = Article::all();
        return view('admin.articles.index', compact('articles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::whereStatus(1)->get();
        $tags = Tag::whereStatus(1)->get();
        return view('admin.articles.create', compact('categories', 'tags'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ArticleRequest $request)
    {
        $url = $this->uploadImages($request->file('image'));

        $article = auth()->user()->articles()->create($request->all());
        Image::create([
            'url' => $url,
            'imageable_id' => $article->id,
            'imageable_type' => get_class($article),
        ]);

        $article->categories()->sync($request->input('category_id'));

        if ($request->input('tag_id')) {
            foreach ($request->input('tag_id') as $id) {
                $article->tags()->attach(array_merge(['tag_id' => $id]), [
                    'taggable_id' => $article->id,
                    'taggable_type' => get_class($article),
                ]);
            }
        }

        return redirect(route('articles.index'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function edit(Article $article)
    {
        $categories = Category::whereStatus(1)->get();
        $tags = Tag::whereStatus(1)->get();
        return view('admin.articles.edit', compact('article', 'categories', 'tags'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function update(ArticleRequest $request, Article $article)
    {
        $file = $request->file('image');
        if ($file) {
            $url = $this->uploadImages($request->file('image'));
            $article->image->update([
                'url' => $url
            ]);
        }

        $article->update($request->all());
        $article->categories()->sync($request->input('category_id'));

        if ($request->input('tag_id')) {
            foreach ($request->input('tag_id') as $id) {
                $article->tags()->sync(array_merge(['tag_id' => $id]), [
                    'taggable_id' => $article->id,
                    'taggable_type' => get_class($article),
                ]);
            }
        }

        return redirect(route('articles.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function delete(Request $request)
    {
        $article = Article::findOrFail($request->id);
        $article->delete();
    }

    public function status(Request $request)
    {
        $article = Article::findOrFail($request->id);
        $article->status = $request->status;
        $article->save();
    }
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Article;

class ArticleController extends Controller
{
    public function index()
    {
        $articles = Article::latest()->simplePaginate(10);
        $sidebarPost = Article::latest()->take(5)->get();

        return view('ui.blog.index', compact('articles', 'sidebarPost'));
    }

    public function single(Article $article)
    {
        $comments = $article->comments()->where('status', 1)->where('reply_id', 0)->latest()->with(['childs' => function ($query) {
            $query->where('status', 1)->latest();
        }])->simplePaginate(5);
        
        $sidebarPost = Article::latest()->take(5)->get();
        return view('ui.blog.single', compact('article', 'comments', 'sidebarPost'));
    }
}

resources/views/admin/articles/create.blade.php
@extends('admin.layouts.master')
@section('title' , 'ثبت مقاله')

@section('scripts')
<script src="//cdn.ckeditor.com/4.13.1/full/ckeditor.js"></script>
<script>
  var editor = CKEDITOR.replace('body', {
    language: 'fa',
    filebrowserUploadMethod : 'form',
    filebrowserUploadUrl: "{{route('admin.upload')}}"
  });
</script>
@endsection

@section('content')
<section>
  <div class="row">
    <div class="col-12">
      <div class="card-box">
        <div class="head-section">
          <h4>ثبت مقاله جدید</h4>
          <a href="{{ route('articles.index') }}" class="btn btn-primary btn-sm">مشاهده مقالات</a>
        </div>
        <hr>
        @include('Admin.section.errors')
        <div class="row">
          <div class="col-lg-12">
            <form class="form-horizontal" action="{{ route('articles.store') }}" method="post"
              enctype="multipart/form-data">
              @csrf
              <div class="form-group">
                <label for="title">عنوان</label>
                <input type="text" class="form-control" name="title" value="{{old('title')}}">
              </div>
              <div class="form-group">
                <label for="description">توضیحات کوتاه</label>
                <textarea class="form-control" name="description" id="description" rows="3">{{old('description')}}</textarea>
              </div>
              <div class="form-group">
                <label for="body">متن</label>
                <textarea class="form-control" name="body" id="body" rows="3">{{old('body')}}</textarea>
              </div>
              <div class="form-group">
                <label for="image">تصویر</label>
                <input type="file" class="form-control" name="image" id="image" />
              </div>
              <div class="form-group">
                <label for="category_id">دسته بندی</label>
                <select name="category_id[]" class="selectpicker" multiple data-selected-text-format="count > 6"
                  data-live-search="true" data-style="btn btn-outline-primary">
                  @foreach ($categories as $category)
                  <option value="{{$category->id}}">{{$category->name}}</option>
                  @endforeach
                </select>
              </div>
              <div class="form-group">
                <label for="tag_id">برچسب</label>
                <select name="tag_id[]" class="selectpicker" multiple data-selected-text-format="count > 6"
                  data-live-search="true" data-style="btn btn-outline-primary">
                  @foreach ($tags as $tag)
                  <option value="{{$tag->id}}">{{$tag->name}}</option>
                  @endforeach
                </select>
              </div>
              <br>
              <div class="form-group">
                <button type="submit" class="btn btn-success btn-block">ثبت مقاله</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
@endsection

resources/views/admin/articles/edit.blade.php
@extends('admin.layouts.master')
@section('title' , 'ویرایش مقاله')

@section('scripts')
<script src="//cdn.ckeditor.com/4.13.1/full/ckeditor.js"></script>
<script>
  var editor = CKEDITOR.replace('body', {
    language: 'fa',
    filebrowserUploadMethod : 'form',
    filebrowserUploadUrl: "{{route('admin.upload')}}"
  });
</script>
@endsection

@section('content')
<section>
  <div class="row">
    <div class="col-12">
      <div class="card-box">
        <div class="head-section">
          <h4>ویرایش مقاله</h4>
          <a href="{{ route('articles.index') }}" class="btn btn-primary">مشاهده مقالات</a>
        </div>
        <hr>
        @include('Admin.section.errors')
        <div class="row">
          <div class="col-lg-12">
            <form class="form-horizontal" action="{{ route('articles.update', ['article' => $article->id]) }}"
              method="post" enctype="multipart/form-data">
              @csrf
              @method('PATCH')
              <div class="form-group">
                <label for="title">عنوان مقاله</label>
                <input type="text" class="form-control" name="title" value="{{$article->title}}">
              </div>
              
              <div class="form-group">
                <label for="description">توضیحات کوتاه</label>
                <textarea class="form-control" name="description" id="description" rows="3">{{$article->description}}</textarea>
              </div>
              <div class="form-group">
                <label for="body">متن مقاله</label>
                <textarea class="form-control" name="body" rows="3">{{$article->body}}</textarea>
              </div>
              <div class="form-group">
                <div class="col-sm-12">
                  <label for="image" class="control-label">تصویر مقاله</label>
                  <input type="file" class="form-control" name="image" id="image"
                    placeholder="تصویر مقاله را وارد کنید">
                </div>
                <br>
                <div class="col-sm-12">
                  <div class="row">
                    @if ($article->image)
                      <a href="{{ asset('storage/' . $article->image->url) }}" target="blanck"><img src="{{ asset('storage/' . $article->image->url)}}" style="width:100px;height:100px;"></a>
                    @endif
                  </div>
                </div>
              </div>
              <div class="form-group">
                <label for="category_id">دسته بندی</label>
                <select name="category_id[]" class="selectpicker" multiple data-selected-text-format="count > 6"
                  data-live-search="true" data-style="btn btn-outline-primary">
                  @foreach ($categories as $category)
                  <option value="{{$category->id}}"
                    {{in_array(trim($category->id) , $article->categories->pluck('id')->toArray()) ? 'selected' : ''}}>
                    {{$category->name}}
                  </option>
                  @endforeach
                </select>
              </div>
              <div class="form-group">
                <label for="tag_id">برچسب</label>
                <select name="tag_id[]" class="selectpicker" multiple data-selected-text-format="count > 6"
                  data-live-search="true" data-style="btn btn-outline-primary">
                  @foreach ($tags as $tag)
                  <option value="{{$tag->id}}"
                    {{in_array(trim($tag->id) , $article->tags->pluck('id')->toArray()) ? 'selected' : ''}}>
                    {{$tag->name}}
                  </option>
                  @endforeach
                </select>
              </div>
              <br>
              <div class="form-group">
                <button type="submit" class="btn btn-success btn-block">ویرایش مقاله</button>
                <a href="{{ route('articles.index') }}" class="btn btn-secondary btn-block">کنسل</a>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
@endsection

resources/views/admin/articles/index.blade.php
@extends('admin.layouts.master')
@section('title' , 'مقالات')

@section('content')
<section>
    <div class="row">
        <div class="col-12">
            <div class="card-box">
                <div class="head-section">
                    <h4>مقالات</h4>
                    <a href="{{ route('articles.create') }}" class="btn btn-primary btn-sm">ایجاد مقاله جدید</a>
                </div>
                <p class="text-muted font-13 m-b-30">
                    تمام مقالات در زیر به نمایش گذاشته شده است.
                </p>
                <div class="table-responsive-sm">
                    <table id="datatable" class="table table-bordered table-hover dt-responsive">
                        <thead>
                            <tr>
                                <th>عنوان</th>
                                <th>تصویر</th>
                                <th>نویسنده</th>
                                <th>دسته ها</th>
                                <th>تنظیمات</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($articles as $article)
                            <tr>
                                <td><a href="{{$article->path()}}">{{$article->title}}</a></td>
                                <td>
                                    @if ($article->image)
                                    <a href="{{ asset('storage/' . $article->image->url) }}" target="blanck"><img src="{{ asset('storage/' . $article->image->url) }}" style="width:70px;height:70px;"></a>
                                    @endif
                                </td>
                                <td>{{$article->user->name}}</td>
                                <td>
                                    <ul>
                                        @foreach ($article->categories->pluck('name') as $category)
                                        <li>{{$category}}</li>
                                        @endforeach
                                    </ul>
                                </td>
                                <td>
                                    <div class="btn-group-sm d-flex justify-content-xl-between">
                                        <input type="checkbox" data-id="{{ $article->id }}" name="status"
                                            class="js-switch" {{ $article->status == 1 ? 'checked' : '' }}>
                                        <a href="{{ route('articles.edit', ['article' => $article->id]) }}"
                                            class="btn btn-sm" title="ویرایش">
                                            <i class="fas fa-edit"></i>
                                        </a>
                                        <a href="{{ route('articles.delete', ['article' => $article->id]) }}"
                                            title="حذف" class="btn btn-sm deleted" data-id="{{ $article->id }}">
                                            <i class="fas fa-trash text-danger"></i>
                                        </a>
                                    </div>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- end row -->
</section>
@endsection

@section('styles')
{{-- Switchery Style --}}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/switchery/0.8.2/switchery.min.css">
@endsection

@section('scripts')

{{-- Switchery Scripts --}}
<script src="https://cdnjs.cloudflare.com/ajax/libs/switchery/0.8.2/switchery.min.js"></script>
<script>
    let elems = Array.prototype.slice.call(document.querySelectorAll('.js-switch'));

    elems.forEach(function(html) {
        let switchery = new Switchery(html,  { size: 'small' });
    });
</script>

{{-- Change Status and Confirm Delete --}}
<script>
    // Change Status 
    $(document).ready(function(){
        $('.js-switch').change(function () {
        let status = $(this).prop('checked') === true ? 1 : 0;
        let id = $(this).data('id');
        $.ajax({
            type: "GET",
            dataType: "json",
            url: '{{ route('articles.status') }}',
            data: {'status': status, 'id': id}
            });
        });
    });

//  Delete Confirm 
    $('.deleted').on('click', function (e) {
        e.preventDefault();

        let le = $(this);
        let url = le.attr('href');
        let CSRF_TOKEN = $('meta[name="csrf-token"]').attr('content');
        let id = $(this).data('id');

        const swalWithBootstrapButtons = Swal.mixin({
        customClass: {
            confirmButton: 'btn btn-success',
            cancelButton: 'btn btn-danger'
        },
        buttonsStyling: false
        })

        swalWithBootstrapButtons.fire({
            title: 'مطمئن هستید?',
            text: "بعد از حذف شما قادر به بازیابی اطلاعات نیستید!",
            type: 'warning',
            showCancelButton: true,
            confirmButtonText: 'حذف',
            cancelButtonText: 'کنسل',
            reverseButtons: true
        }).then((result) => {
            if (result.value) {
                $.ajax({
                    url: url,
                    type: "POST",
                    data: {
                        'id': id,
                        '_token': CSRF_TOKEN
                    },
                    success: function (res) {  
                        
                        swalWithBootstrapButtons.fire(
                                'حذف شد!',
                                'اطلاعات شما به طور کامل حذف شد',
                                'success'
                            )
                            setInterval(function() {location.reload();}, 2000);
                    }
                });
            }else if (result.dismiss === Swal.DismissReason.cancel) {
                swalWithBootstrapButtons.fire(
                'کنسل شد',
                'اطلاعات موردنظر هنوز در دسترس شماست :)',
                'error'
                )
            }
        });
    });

</script>
@endsection